"""Tests for the release notes drafter feature."""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.features import release_notes


@pytest.fixture()
def push_payload() -> dict:
    return {
        "ref": "refs/tags/v1.2.0",
        "repository": {"id": 1, "full_name": "test-org/test-repo", "default_branch": "main"},
        "installation": {"id": 999},
    }


@pytest.mark.asyncio
async def test_release_notes_run_returns_string(push_payload: dict):
    mock_result = (
        "## 📋 Release Notes Draft\n\n### v1.2.0\n\n"
        "#### ✨ New Features\n- Upload size validation (#7)\n\n"
        "---\n*Generated by MaintainerCopilot powered by NVIDIA Nemotron-3-Super*"
    )

    with (
        patch("app.features.release_notes.GitHubClient") as MockClient,
        patch("app.features.release_notes.run_agent", new_callable=AsyncMock) as mock_agent,
    ):
        mock_client = MagicMock()
        mock_client.get_merged_prs.return_value = [
            {"number": 7, "title": "Fix upload validation", "body": "", "labels": ["bug"]}
        ]
        MockClient.return_value = mock_client
        mock_agent.return_value = mock_result

        result = await release_notes.run(push_payload)

    assert isinstance(result, str)
    assert "Release Notes" in result


@pytest.mark.asyncio
async def test_release_notes_no_prs_returns_graceful_message(push_payload: dict):
    with (
        patch("app.features.release_notes.GitHubClient") as MockClient,
        patch("app.features.release_notes.run_agent", new_callable=AsyncMock) as mock_agent,
    ):
        mock_client = MagicMock()
        mock_client.get_merged_prs.return_value = []
        MockClient.return_value = mock_client

        result = await release_notes.run(push_payload)

    assert "No recently merged pull requests" in result
    mock_agent.assert_not_called()


@pytest.mark.asyncio
async def test_release_notes_groups_prs(push_payload: dict):
    with (
        patch("app.features.release_notes.GitHubClient") as MockClient,
        patch("app.features.release_notes.run_agent", new_callable=AsyncMock) as mock_agent,
    ):
        mock_client = MagicMock()
        mock_client.get_merged_prs.return_value = [
            {"number": 1, "title": "Add dark mode", "body": "", "labels": ["enhancement"]},
            {"number": 2, "title": "Fix login crash", "body": "", "labels": ["bug"]},
        ]
        MockClient.return_value = mock_client
        mock_agent.return_value = "release notes"

        await release_notes.run(push_payload)

        user_message: str = mock_agent.call_args[0][1]
        assert "#1" in user_message
        assert "#2" in user_message
