"""Feature 5: Release note drafter from merged pull requests."""

import logging

from app.agent.core import run_agent
from app.agent.prompts import RELEASE_NOTES_PROMPT
from app.github.client import GitHubClient

logger = logging.getLogger(__name__)


async def run(data: dict, since_tag: str | None = None) -> str:
    """
    Draft release notes from recently merged pull requests.

    Can be triggered by a `/copilot release-notes` comment or a push
    to the default branch. Returns a formatted markdown draft.
    """
    repo_full_name: str = data["repository"]["full_name"]
    installation_id: int = data["installation"]["id"]

    client = GitHubClient(installation_id)
    merged_prs = client.get_merged_prs(repo_full_name, since_tag=since_tag)

    if not merged_prs:
        return (
            "## 📋 Release Notes Draft\n\n"
            "No recently merged pull requests found.\n\n"
            "---\n*Generated by MaintainerCopilot powered by NVIDIA Nemotron-3-Super*"
        )

    pr_list = "\n".join(
        f"- #{pr['number']}: {pr['title']} — labels: {', '.join(pr['labels']) or 'none'}"
        for pr in merged_prs
    )

    user_message = (
        f"Repository: {repo_full_name}\n\n"
        f"Recently merged pull requests:\n{pr_list}\n\n"
        "Please draft release notes categorizing these changes."
    )

    context = {
        "github_client": client,
        "repo_full_name": repo_full_name,
        "feature": "release_notes",
    }

    result = await run_agent(RELEASE_NOTES_PROMPT, user_message, context)
    logger.info(
        "Release notes drafted for %s", repo_full_name,
        extra={"feature": "release_notes", "repo": repo_full_name},
    )
    return result
